name: menu-idp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - paddlepaddle==2.6.1     # <-- add this line
      - paddleocr
      - ultralytics==8.3.0
      - opencv-python-headless
      - numpy
      - Pillow
      - tqdm
      - pydantic
      - pyyaml
      - python-dotenv
      - transformers==4.43.4
      - tokenizers
      - shapely
